has("GSM847777","title", "kidney 13 wks rep 1").
has("GSM847777","geo_accession", "GSM847777").
has("GSM847777","status", "Public on Jul 10 2013").
has("GSM847777","submission_date", "Dec 12 2011").
has("GSM847777","last_update_date", "Jul 10 2013").
has("GSM847777","type", "RNA").
has("GSM847777","channel_count", "1").
has("GSM847777","source_name_ch1", "kidney 13 wks").
has("GSM847777","organism_ch1", "Mus musculus").
has("GSM847777","taxid_ch1", "10090").
has("GSM847777","characteristics_ch1", "tissue: kidney").
has("GSM847777","treatment_protocol_ch1", "None").
has("GSM847777","growth_protocol_ch1", "Female C57BL6/J mice were marked and randomized at the day of birth in different groups; i.e. longevity cohorts (previously described in Wijnhoven et al. (2005; DNA Repair (Amst) 4: 1314-1324.), or cross-sectional cohorts in which the mice were sacrificed at fixed time points. Cross-sectional cohorts C57BL6/J mice were sacrificed at a fixed age of 13, 26, 52, 78, 104 and 130 weeks. During the entire experiment, animals were kept in the same stringently controlled pathogen free (spf) environment, fed ad libitum and kept under a normal day/night rhythm. The microbiological status of the cohorts was monitored every 3 months.").
has("GSM847777","molecule_ch1", "total RNA").
has("GSM847777","extract_protocol_ch1", "Total RNA was isolated from liver, kidney, spleen, lung and brain, using the RNeasy Midi Kit (Qiagen, Valencia, CA, USA;). RNA quality was tested using automated gel electrophoresis (Bioanalyzer 2100; Agilent technologies, Amstelveen, the Netherlands). Only RIN > 7 were processed further.").
has("GSM847777","label_ch1", "biotin").
has("GSM847777","label_protocol_ch1", "In short, biotin-labeled cRNA samples were prepared as described in the Affymetrix expression analysis technical manual (Affymetrix) using 3 μg of purified total RNA as template for the reaction. For this the One-Cycle cDNA Synthesis Kit (Affymetrix) was used.").
has("GSM847777","hyb_protocol", "The labeled cDNA was hybridized to the Mouse GeneChip 430 2.0 (Affymetrix, Santa Clara, CA, USA). The GeneChip Hybridization, Wash and Stain Kit (Affymetrix, CA) was used for the hybridizations according to the protocol of the manufacturer.").
has("GSM847777","scan_protocol", "GeneChips were scanned using the Affymetrix GCS3000 HR GeneChip Scanner and GCOS").
has("GSM847777","data_processing", "The data were analyzed with the R statistical programming language (http://cran.r-project.org/) and the bioconductor affy package. The raw data were annotated according de Leeuw et al. (2008; BMC Res Notes. 19: 1-66 (hence the odd probeset identifiers)) and normalized using the robust multi-array average (RMA) algorithm (Irizarry et al., 2003; Biostatistics 4: 249-264). Please note that we corrected the data for labelling-batch effects in the paper.").
has("GSM847777","platform_id", "GPL14996").
has("GSM847777","contact_name", "Martijs,,Jonker").
has("GSM847777","contact_email", "m.j.jonker@uva.nl").
has("GSM847777","contact_department", "Microarray Department").
has("GSM847777","contact_institute", "University of Amsterdam").
has("GSM847777","contact_address", "Science Park 904").
has("GSM847777","contact_city", "Amsterdam").
has("GSM847777","contact_zip/postal_code", "1090 GE").
has("GSM847777","contact_country", "Netherlands").
has("GSM847777","supplementary_file", "ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM847nnn/GSM847777/suppl/GSM847777_IOP_001.CEL.gz").
has("GSM847777","series_id", "GSE34378").
has("GSM847777","data_row_count", "35283").
